In [1]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [2]:
# Loading the dataset
import os
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
path= '/content/drive/MyDrive/seeds.data'
features = ['Area',
            'Perimeter',
            'Compactness',
            'Length of kernel',
            'Width of kernel',
            'Asymmetry coefficient',
            ' groove.']
df= pd.read_csv(path,header=None,names=features + ['target'])
display(df)
#df['Area'] = df['Area'].astype(float)
print(df.dtypes)

Area  Perimeter  Compactness Length of kernel Width of kernel  \
0     Area  Perimeter  Compactness           Length           Width   
1    15.26      14.84        0.871            5.763           3.312   
2    14.88      14.57       0.8811            5.554           3.333   
3    14.29      14.09        0.905            5.291           3.337   
4    13.84      13.94       0.8955            5.324           3.379   
..     ...        ...          ...              ...             ...   
206  12.19       13.2       0.8783            5.137           2.981   
207  11.23      12.88       0.8511             5.14           2.795   
208   13.2      13.66       0.8883            5.236           3.232   
209  11.84      13.21       0.8521            5.175           2.836   
210   12.3      13.34       0.8684            5.243           2.974   

    Asymmetry coefficient  groove. target  
0               Asymmetry   Groove  Class  
1                   2.221     5.22      1  
2                   1.018    4.956      1  
3                   2.699    4.825      1  
4                   2.259    4.805      1  
..                    ...      ...    ...  
206                 3.631     4.87      3  
207                 4.325    5.003      3  
208                 8.315    5.056      3  
209                 3.598    5.044      3  
210                 5.637    5.063      3  

[211 rows x 8 columns]

Area                     object
Perimeter                object
Compactness              object
Length of kernel         object
Width of kernel          object
Asymmetry coefficient    object
 groove.                 object
target                   object
dtype: object


In [3]:
# Converting the features from in X Array and class in Y array
X = df.iloc[1:,[0,1,2,3,4,5,6]].values
X=X.astype('float64')
print(X.shape)
y = df.loc[1:,'target']
y=y.astype('int64')
#print (y)
print('Class labels:', np.unique(y))

(210, 7)
Class labels: [1 2 3]


In [4]:
# Randomly choosing 5% indices from the dataset and replace with NaN
random_rows = [np.random.randint(0,210,74)] # 210*7*5% = 74
random_cols = [np.random.randint(0,7,74)]
random_rows,random_cols
X[random_rows, random_cols] = np.nan
display(X)

array([[15.26  , 14.84  ,  0.871 , ...,  3.312 ,  2.221 ,  5.22  ],
       [14.88  , 14.57  ,  0.8811, ...,  3.333 ,  1.018 ,  4.956 ],
       [14.29  , 14.09  ,  0.905 , ...,  3.337 ,  2.699 ,  4.825 ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  3.232 ,  8.315 ,  5.056 ],
       [11.84  , 13.21  ,  0.8521, ...,  2.836 ,  3.598 ,  5.044 ],
       [12.3   , 13.34  ,  0.8684, ...,  2.974 ,  5.637 ,  5.063 ]])

In [5]:
#Counting the numbers of NaN value in Dataframe
np.count_nonzero(np.isnan(X))

67

In [6]:
#Creating concatenated array
import numpy as np

#Create NumPy arrays
arr = np.array(X)
arr1 = np.array(y)

# Use concatenate() to join two arrays
con = np.column_stack((arr, arr1))
print(con.shape)
display(con)

(210, 8)


array([[15.26  , 14.84  ,  0.871 , ...,  2.221 ,  5.22  ,  1.    ],
       [14.88  , 14.57  ,  0.8811, ...,  1.018 ,  4.956 ,  1.    ],
       [14.29  , 14.09  ,  0.905 , ...,  2.699 ,  4.825 ,  1.    ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  8.315 ,  5.056 ,  3.    ],
       [11.84  , 13.21  ,  0.8521, ...,  3.598 ,  5.044 ,  3.    ],
       [12.3   , 13.34  ,  0.8684, ...,  5.637 ,  5.063 ,  3.    ]])

In [7]:
#Converting the concatenated array into df 
import numpy as np
import pandas as pd

df = pd.DataFrame(con)
display (df)


0      1       2      3      4      5      6    7
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220  1.0
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1.0
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1.0
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1.0
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1.0
..     ...    ...     ...    ...    ...    ...    ...  ...
205  12.19  13.20  0.8783  5.137  2.981    NaN  4.870  3.0
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003  3.0
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056  3.0
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044  3.0
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063  3.0

[210 rows x 8 columns]

In [8]:
#Replacing the Nan values with Median
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='median')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[15.26  , 14.84  ,  0.871 , ...,  2.221 ,  5.22  ,  1.    ],
       [14.88  , 14.57  ,  0.8811, ...,  1.018 ,  4.956 ,  1.    ],
       [14.29  , 14.09  ,  0.905 , ...,  2.699 ,  4.825 ,  1.    ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  8.315 ,  5.056 ,  3.    ],
       [11.84  , 13.21  ,  0.8521, ...,  3.598 ,  5.044 ,  3.    ],
       [12.3   , 13.34  ,  0.8684, ...,  5.637 ,  5.063 ,  3.    ]])

In [9]:
#Printing imputed df
df = pd.DataFrame(imputed_data)
display (df)

0      1       2      3      4       5      6    7
0    15.26  14.84  0.8710  5.763  3.312  2.2210  5.220  1.0
1    14.88  14.57  0.8811  5.554  3.333  1.0180  4.956  1.0
2    14.29  14.09  0.9050  5.291  3.337  2.6990  4.825  1.0
3    13.84  13.94  0.8955  5.324  3.379  2.2590  4.805  1.0
4    16.14  14.99  0.9034  5.658  3.562  1.3550  5.175  1.0
..     ...    ...     ...    ...    ...     ...    ...  ...
205  12.19  13.20  0.8783  5.137  2.981  3.5975  4.870  3.0
206  11.23  12.88  0.8511  5.140  2.795  4.3250  5.003  3.0
207  13.20  13.66  0.8883  5.236  3.232  8.3150  5.056  3.0
208  11.84  13.21  0.8521  5.175  2.836  3.5980  5.044  3.0
209  12.30  13.34  0.8684  5.243  2.974  5.6370  5.063  3.0

[210 rows x 8 columns]

In [10]:
#Checking number of Nan values in df
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [11]:
X = df.iloc[:, [5,6]].values
X=X.astype('float64')
#print(X)
y = df.loc[:, 7].values
y=y.astype('int64')
#print (y)
print('Class labels:', np.unique(y))

Class labels: [1 2 3]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

In [13]:
print('Labels counts in y:', np.bincount(y)[1:])
>>> print('Labels counts in y_train:', np.bincount(y_train)[1:])
>>> print('Labels counts in y_test:', np.bincount(y_test)[1:])

Labels counts in y: [70 70 70]
Labels counts in y_train: [58 68 63]
Labels counts in y_test: [12  2  7]


In [14]:
from sklearn.preprocessing import StandardScaler
>>> sc = StandardScaler()
>>> sc.fit(X_train)
>>> X_train_std = sc.transform(X_train)
>>> X_test_std = sc.transform(X_test)

In [15]:
# Logistic Regression Classifier 
log_reg = LogisticRegression()
log_reg.fit(X_train_std,y_train)
y_pred= log_reg.predict(X_test_std)
print('predicted:',y_pred)
print('true class:', np.array(y_test))

predicted: [1 3 3 3 1 3 1 3 3 3 2 1 1 1 1 3 3 1 1 1 1]
true class: [1 3 1 3 1 2 1 3 3 3 2 1 1 1 1 3 3 1 1 1 1]


In [16]:
print('Misclassified examples: %d' % (y_test != y_pred).sum())

Misclassified examples: 2


In [17]:
from sklearn.metrics import accuracy_score
>>> print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 0.905
